version: '3.8'

services:
  api:
    build:
      context: ./api
    expose:
      - "9000"
    ports:
      - "9080:9000"
    volumes:
      - ./api/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ger-vec
    depends_on:
      - redis
      - postgres

  app:
    build:
      context: ./app
      args:
        - API_URL=${API_URL}
    expose:
      - "5173"
    networks:
      - ger-vec

  redis:
    image: redis:latest
    container_name: redis-container
    expose:
      - "6379"
    networks:
      - ger-vec

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: api
    expose:
      - "5432"
    networks:
      - ger-vec

  nginx:
    image: nginx:1.24.0
    container_name: gateway-container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5174:80"
    command: [ "sh", "-c", "nginx -g 'daemon off;' && nginx -s reload" ]
    depends_on:
      - api
      - app
    networks:
      - ger-vec

volumes:
  postgres-data:
    driver: local

networks:
  ger-vec:
    driver: bridge